# Generated by Django 2.2.4 on 2020-01-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='attachment',
            new_name='image',
        ),
    ]
