# Generated by Django 2.2.4 on 2020-01-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
