# Generated by Django 2.2.4 on 2020-01-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
