# Generated by Django 2.2.4 on 2020-02-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200206_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seo',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
