# Generated by Django 2.2.4 on 2020-02-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200212_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
