# Generated by Django 2.2.4 on 2020-02-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200219_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemspec',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
