# Generated by Django 2.2.4 on 2020-03-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200318_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='address',
        ),
    ]
