# Generated by Django 2.2.4 on 2020-03-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200324_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_variations', to='core.Variation'),
        ),
    ]
