# Generated by Django 2.2.4 on 2020-04-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200413_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
