# Generated by Django 2.2.4 on 2020-06-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_seo_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
