# Generated by Django 2.2.4 on 2020-06-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='alt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
