# Generated by Django 2.2.4 on 2020-06-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20200612_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
