# Generated by Django 2.2.4 on 2020-08-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_itemimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='doc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='doc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
