# Generated by Django 2.2.4 on 2020-09-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20200912_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='out_of_stock_sale',
            field=models.BooleanField(default=False),
        ),
    ]
