from django.urls import path
from .views import (
    UserIDView,
    ItemDetail,
    ItemList,
    AddToCartView,
    OrderDetailView,
    OrderQuantityUpdateView,
    PaymentView,
    AddCouponView,
    CountryListView,
    AddressListView,
    AddressCreateView,
    AddressUpdateView,
    AddressDeleteView,
    OrderItemDeleteView,
    PaymentListView,
    CategoryList,
    CategoryDetail,
    BrandList,
    BrandDetail,
    Search,
    KeywordSearch,
    WishlistToggle,
    ItemSpecList,
    SliderList,
)

urlpatterns = [
    path('user-id/', UserIDView.as_view(), name='user-id'),
    path('countries/', CountryListView.as_view(), name='country-list'),
    path('addresses/', AddressListView.as_view(), name='address-list'),
    path('addresses/create/', AddressCreateView.as_view(), name='address-create'),
    path('addresses/<pk>/update/',
         AddressUpdateView.as_view(), name='address-update'),
    path('addresses/<pk>/delete/',
         AddressDeleteView.as_view(), name='address-delete'),
    path('products/', ItemList.as_view(), name='product-list'),
    path('products/<str:slug>/', ItemDetail.as_view(), name='product-detail'),
    path('products/<str:slug>/wishlist', WishlistToggle.as_view(), name='product-wishlist'),
    path('products/<str:slug>/specs/', ItemSpecList.as_view(), name='product-specs'),
    path('categories/', CategoryList.as_view(), name='category'),
    path('categories/<str:slug>/', CategoryDetail.as_view(), name='category-get'),
    path('brands/', BrandList.as_view(), name='category'),
    path('brands/<str:slug>/', BrandDetail.as_view(), name='category-get'),
    path('search/', Search.as_view(), name='search-get'),
    path('keywordsearch/', KeywordSearch.as_view(), name='keyword-search-get'),
    path('add-to-cart/', AddToCartView.as_view(), name='add-to-cart'),
    path('order-summary/', OrderDetailView.as_view(), name='order-summary'),
    path('checkout/', PaymentView.as_view(), name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('order-items/<pk>/delete/',
         OrderItemDeleteView.as_view(), name='order-item-delete'),
    path('order-item/update-quantity/',
         OrderQuantityUpdateView.as_view(), name='order-item-update-quantity'),
    path('payments/', PaymentListView.as_view(), name='payment-list'),
    path('sliders/', SliderList.as_view(), name='slider-list'),

]
